FROM node:14.15.4-buster
FROM cypress/base

RUN apt-get update && \
  apt-get install --no-install-recommends -y \
  libgtk2.0-0 \
  libgtk-3-0 \
  libnotify-dev \
  libgconf-2-4 \
  libgbm-dev \
  libnss3 \
  libxss1 \
  libasound2 \
  libxtst6 \
  xauth \
  xvfb

WORKDIR /app

COPY ./package*.json ./

RUN npm i

ARG CYPRESS_RECORD_KEY

ENV CYPRESS_RECORD_KEY ${CYPRESS_RECORD_KEY}

COPY ./ ./

