FROM node:14.19.2

WORKDIR /app

COPY ./package.json ./

RUN rm -rf ./node_modules
RUN rm -f ./package-lock.json

RUN npm i

ARG CYPRESS_RECORD_KEY

ENV CYPRESS_RECORD_KEY ${CYPRESS_RECORD_KEY}

COPY ./ ./

CMD ["npx cypress run --record --key ${CYPRESS_RECORD_KEY}"]