FROM node:14.19.2

WORKDIR /app

COPY ./package.json ./

RUN npm i -g npx

ARG CYPRESS_RECORD_KEY

ENV CYPRESS_RECORD_KEY ${CYPRESS_RECORD_KEY}

COPY ./ ./

CMD ["npx cypress run --record --key ${CYPRESS_RECORD_KEY}"]